### ISSUE TITLE
on import "<command-line>: warning: ISO C++11 requires whitespace after the macro name"

### ISSUE THREAD

**Issue by MagunRa** [multiphenics/multiphenicsx#1]
Hi, 

when import multiphenicsx I get the warning `<command-line>: warning: ISO C++11 requires whitespace after the macro name`.
It seems not to stop the import, but it is really irritating.

Best Regards,
Moritz

**Comment by francesco-ballarin** [comment]
Hi Moritz,
* does it happen every time (across different runs) you import multiphenicsx, or only the first time?
* can you share some info on your system (e.g., compiler version)?

Thanks,
Francesco

**Comment by MagunRa** [comment]
Hi Francesco,
I am using the jupyter notebook from the docker image (on a windows host, if this matters).
It happens only the first time I import multiphenicsx.

Rest regards,
Moritz

**Comment by francesco-ballarin** [comment]
Hi @MagunRa , can you check if https://github.com/multiphenics/multiphenicsx/commit/ed18432ebba9f65a28e886ff6e42c85d89d8614a fixes the issue for you?

**Comment by MagunRa** [comment]
Yes it does resolve the warning. 
Best Regards

**Comment by francesco-ballarin** [comment]
Closed via https://github.com/multiphenics/multiphenicsx/commit/ed18432ebba9f65a28e886ff6e42c85d89d8614a
