### ISSUE TITLE
Migration to `nanobind` in progress

### ISSUE THREAD

**Issue by francesco-ballarin** [multiphenics/multiphenicsx#19]
After the upstream merge of https://github.com/FEniCS/dolfinx/pull/2820, `dolfinx` has moved from `pybind11` to `nanobind`. 
`multiphenicsx` will have to move from `pybind11` to `nanobind` too, and such migration is currently in progress. Until this is done, `multiphenicsx` will be behind `dolfinx` main, which means e.g. that users installing `multipenicsx` from a current `dolfinx/dolfinx:nightly` docker image are seeing errors on installation.

**Comment by bbbyyfff** [comment]
Hi Francesco,

Would you mind providing a stable version combination of `dolfinx` and `multiphenicsx`?

Thank you very much!

Yifei

**Comment by francesco-ballarin** [comment]
See https://multiphenics.github.io/installing.html#compatibility-with-upstream-releases to see how to install a version of `multiphenicsx` compatible with a specific `dolfinx` release.

Is this what you were looking for?

**Comment by bbbyyfff** [comment]
> See https://multiphenics.github.io/installing.html#compatibility-with-upstream-releases to see how to install a version of `multiphenicsx` compatible with a specific `dolfinx` release.
> 
> Is this what you were looking for?

My bad, should have noticed this.

**Comment by francesco-ballarin** [comment]
Done in 0592c6e625f2a1f2b0c2b254b1d017e3ece37ec9
