### ISSUE TITLE
Problem with complex version of petsc

### ISSUE THREAD

**Issue by AlirezaSharif** [multiphenics/multiphenicsx#23]
Hi,

I was trying to work with complex numbers in FEniCSx and multiphenicsx and to do so, installed the proper version using:
``` bash
conda create -n env3-12 -c conda-forge python=3.12 fenics-dolfinx mpich
```
Then, I installed multiphenicsx by simply following the instructions [here](https://multiphenics.github.io/installing.html).
However, I could not import multiphenicsx.fem while running my script and got this error:
``` bash
error: 'full_extent' is not a member of 'std::experimental'; did you mean 'std::full_extent'?
  218 |       unrestricted_cell_dofs, c, std::experimental::full_extent);
      |                                                     ^~~~~~~~~~~
In file included from /env3-12-complex/include/dolfinx/fem/DofMap.h:13,
                 from/envs/env3-12-complex/lib/python3.12/site-packages/multiphenicsx/cpp/multiphenicsx/fem/DofMapRestriction.cpp:7:
/envs/env3-12-complex/include/basix/mdspan.hpp:1068:40: note: 'std::full_extent' declared here
 1068 | _MDSPAN_INLINE_VARIABLE constexpr auto full_extent = full_extent_t{ };
      |                                        ^~~~~~~~~~~
error: command '/envs/env3-12-complex/bin/x86_64-conda-linux-gnu-cc' failed with exit code 1
```
Can you help me how to resolve this issue?

**Comment by francesco-ballarin** [comment]
Hi,
there are two sets of instructions in the page you linked. Which of the two did you follow?

**Comment by francesco-ballarin** [comment]
You may want to try and manually apply the change in https://github.com/multiphenics/multiphenicsx/commit/77f39fd8ddb71829edb16b2faf8f32f6a0b682bf to see if that solves the issue. Still, my gut feeling is that you are not following the correct installation instructions.

**Comment by AlirezaSharif** [comment]
Thank you Francesco for your quick reply.
I used the instructions regarding Dolfinx release. I will try your other solution.

**Comment by AlirezaSharif** [comment]
Hi again, 
Uninstalling and installing again solved the problem.
Thanks again @francesco-ballarin
