### ISSUE TITLE
cannot build wrappers from `main` branch with `nanobind` 2.0: read this if you get a compilation error `static_assert(!is_ref || std::is_same_v<T, const char*>`

### ISSUE THREAD

**Issue by francesco-ballarin** [multiphenics/multiphenicsx#27]
Due to a regression in `nanobind` 2.0, it is currently not possible to install the package from `main` branch, unless the patch from https://github.com/wjakob/nanobind/pull/608 is manually applied to the `nanobind` 2.0 installation. There is nothing we can do about this downstream, and this issue will stay open until a new `nanobind` version is released.

This issue only affects users building from the `main` branch, targeting the `main` branch of `dolfinx`. Users who install `multiphenicsx` for `dolfinx` 0.8.0 (or previous releases) are not effected.

**Comment by ordinary-slim** [comment]
Thank you! The branch `nb` does build correctly with the referenced patch.

**Comment by francesco-ballarin** [comment]
> Thank you! The branch `nb` does build correctly with the referenced patch.

Indeed it does, now I'll be merging it into `main` and I'll be deleting it. This issue will stay open.

**Comment by francesco-ballarin** [comment]
The aforementioned PR has been included in `nanobind` 2.1.0, which was released yesterday. `multiphenicsx` now requires `nanobind >= 2.1.0`.
