### ISSUE TITLE
Some puzzles with tutorials/02_navier_stokes

### ISSUE THREAD

**Issue by HYB777** [multiphenics/multiphenicsx#28]
Hello, I have some puzzles with tutorials/02_navier_stokes.

In this demo, I found there is not outlet condition, but it still got a solution?

**Comment by francesco-ballarin** [comment]
If there is no outlet conditions it means that it is a homogeneus Neumann boundary condition. 

Please use https://github.com/multiphenics/multiphenicsx/discussions in future for questions. Issues must be used only for bug reports.
