### ISSUE TITLE
NonlinearProblem/Solver and initial condition

### ISSUE THREAD

**Issue by Raul-Ciria-Aylagas** [multiphenics/multiphenicsx#3]
Hello,

I'm really missing an implementation of the nonlinear solver and nonlinear problem class as in the dolfinx package.
I'm trying to build these objects following the tutorials ( [tutorial_02](https://github.com/multiphenics/multiphenicsx/blob/main/tutorials/02_navier_stokes/tutorial_navier_stokes.ipynb) and [tutorial 6_8](https://github.com/multiphenics/multiphenicsx/blob/main/tutorials/06_optimal_control/tutorial_8_navier_stokes_neumann_control.ipynb)), however I'm having some problems.

First, I assume that I can use the multiphenics vector and matrix creation and assembly even when I have a MixedFunctionSpace (with or without restrictions), is that wrong?
Second, I understand that the update_solutions method updates the block vector (with or without restrictions) into the solution vector, but I don't see how can I update the initial solution of the block vector, could you give me an example?

Find here a MWE with a switch variable called block at line 159 that switch between multiphenicsx and dolfinx solution:
[test_dfx.txt](https://github.com/multiphenics/multiphenicsx/files/8184802/test_dfx.txt)

With block=False, dolfinx solution works, but with block=True, multiphenicsx solution fails. I guess it is because it is not reading the initial value of u_1. I've tried assigning the initial condition of u_1 to the solution vector but i don't know what would be the way to do it.

**Comment by francesco-ballarin** [comment]
Hi @Raul-Ciria-Aylagas ,
nice to see a few FEniCS/multiphenics users migrating to FEniCSx/multiphenicsx.

On the points you raise:
1) I personally see very little point in using MixedElement anymore, now that dolfinx supports block assembly. Unless of course MixedElement is used to store logically contiguous variables (e.g., components of a vector variable, i.e. a VectorElement: that is the only case that IMHO makes sense now). It seems to me that this is not your case.
2) Your combination of  MixedElement and {create, assemble}_{matrix, vector}_block feels wrong to me. dolfinx (and thus multiphenicsx) block assembly is supposed to operate with test/trial functions defined on independent function spaces, while you are trying to use on test/trial subfunctions from a mixed function space. I'd bet that this is one big issue with your code. Can you try updating your code defining two independent P1 FE spaces?
3) On setting an initial guess: I see your point, I'll work on an example.
4) On dolfinx.fem.petsc.NonlinearProblem and dolfinx.nls.petsc.NewtonSolver equivalents in multiphenicsx: I am sorry, but this will not be added. My personal opinion is that a class like NewtonSolver should have never been there in the first place, and that users should always rely on SNES, even if at the beginning it may be a bit painful. This opinion is formed on several personal experiences in which SNES outperformed dolfin/dolfinx built-in Newton solver. Of course I have no say in what dolfinx developers do or don't do :P, but if I see something that I do not feel useful I will be less inclined to port it to multiphenicsx.

Thanks for the feedback!

**Comment by francesco-ballarin** [comment]
Hi,
on item 3: I have shown how to set up initial guesses in all nonlinear tutorials, see the `guess` branch https://github.com/multiphenics/multiphenicsx/tree/guess

@Raul-Ciria-Aylagas , can you help me testing such addition in one of your use cases, e.g. comparing whether starting from the zero vector or a non-zero one makes a difference in terms of convergence that you would expect?

**Comment by Raul-Ciria-Aylagas** [comment]
Hi @francesco-ballarin,

As usual, worked like a charm.  Thanks, it was necessary for equations prone to singularities at zero. I'm leaving here an example with the changes you suggested. I think we can close the issue for now.
Example:  [test_dfx.txt](https://github.com/multiphenics/multiphenicsx/files/8191274/test_dfx.txt)

Thank you very much!
