### ISSUE TITLE
Results visualization problem

### ISSUE THREAD

**Issue by RokyC** [multiphenics/multiphenicsx#4]
itkwidgets module, it seems to be unavailable in the latest version of Jupyterlab.
multiphenicsx.io.plot_mesh(mesh)
Error displaying widget: model not found
Error displaying widget: model not found

**Comment by francesco-ballarin** [comment]
Indeed, see https://github.com/InsightSoftwareConsortium/itkwidgets

```
Note

JupyterLab 3 support is not yet available. JupyterLab 2 or the Jupyter Notebook are possible alternatives.
```

Unfortunately, there is not much we can do, except for switching altogether to something else. Feel free to suggest if you have experience with one of the other interactive backends in `pyvista`: in my experience, I still rate the `itkwidgets` one better than the others.
