### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by mwijnen89** [multiphenics/multiphenicsx#6]
When installing after cloning the repository and using: 'pip3 install .[tutorials]' 
I get the following error:

Processing /home/mick/multiphenicsx
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
ERROR: Invalid requirement: 'nbvalx[notebooks]@ git+https://github.com/multiphenics/nbvalx.git; extra == "tutorials"'

Please advise

**Comment by francesco-ballarin** [comment]
Hi,
that error typically appears when you have old versions of pip (before 22, if I remember correctly).

Please upgrade pip, e.g.
```
python3 -m pip install --upgrade pip
```
and afterwards installation should work correctly
